# syntax=docker/dockerfile:1
# Dockerfile to build the matrixdotorg/synapse:suse docker images which
# don't exist so you have to build them manually.
#
# To build the image, run `docker build` command from the root of the
# synapse repository:
#
#    DOCKER_BUILDKIT=1 docker build -f docker/Dockerfile .
#
# There is an optional PYTHON_VERSION build argument which sets the
# version of python to build against: for example:
#
#    DOCKER_BUILDKIT=1 docker build -f docker/Dockerfile --build-arg PYTHON_VERSION=3.10 .
#

# Irritatingly, there is no blessed guide on how to distribute an application with its
# poetry-managed environment in a docker image. We have opted for
# `poetry export | pip install -r /dev/stdin`, but beware: we have experienced bugs in
# in `poetry export` in the past.

# Custom astral-uv images are ready, moving forward to SLES16.0 which should be ABI compatible with Leap16.0
# Complete glibc and other dependency compatiblity currently being tested.

ARG LEAP_VERSION=leap16
ARG PYTHON_VERSION=313
ARG POETRY_VERSION=2.3.2
ARG GOSU_VER=1.19
ARG SLES_VERSION=16.0
###
### Stage 0: generate requirements.txt
###
### This stage is platform-agnostic, so we can use the build platform in case of cross-compilation.
### 
#FROM --platform=$BUILDPLATFORM ghcr.io/astral-sh/uv:python${PYTHON_VERSION}-${DEBIAN_VERSION} AS requirements
FROM alessmicro/astral-uv:${LEAP_VERSION}-python${PYTHON_VERSION} AS requirements
WORKDIR /synapse

# Copy just what we need to run `poetry export`...
COPY pyproject.toml poetry.lock /synapse/


# If specified, we won't verify the hashes of dependencies.
# This is only needed if the hashes of dependencies cannot be checked for some
# reason, such as when a git repository is used directly as a dependency.
ARG TEST_ONLY_SKIP_DEP_HASH_VERIFICATION

# If specified, we won't use the Poetry lockfile.
# Instead, we'll just install what a regular `pip install` would from PyPI.
ARG TEST_ONLY_IGNORE_POETRY_LOCKFILE

# This silences a warning as uv isn't able to do hardlinks between its cache
# (mounted as --mount=type=cache) and the target directory.
ENV UV_LINK_MODE=copy

# Export the dependencies, but only if we're actually going to use the Poetry lockfile.
# Otherwise, just create an empty requirements file so that the Dockerfile can
# proceed.
ARG POETRY_VERSION
RUN --mount=type=cache,target=/root/.cache/uv \
  if [ -z "$TEST_ONLY_IGNORE_POETRY_LOCKFILE" ]; then \
    uvx --with poetry-plugin-export==1.9.0 \
        poetry@${POETRY_VERSION} export --extras all -o /synapse/requirements.txt ${TEST_ONLY_SKIP_DEP_HASH_VERIFICATION:+--without-hashes}; \
  else \
    touch /synapse/requirements.txt; \
  fi

###
### Stage 1: builder
###
FROM alessmicro/astral-uv:${LEAP_VERSION}-python${PYTHON_VERSION} AS builder

# This silences a warning as uv isn't able to do hardlinks between its cache
# (mounted as --mount=type=cache) and the target directory.
ENV UV_LINK_MODE=copy

# Install rust and ensure its in the PATH
ENV RUSTUP_HOME=/rust
ENV CARGO_HOME=/cargo
ENV PATH=/cargo/bin:/rust/bin:/usr/pgsql-17/bin:$PATH
RUN mkdir /rust /cargo

RUN curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain stable --profile minimal

# arm64 builds consume a lot of memory if `CARGO_NET_GIT_FETCH_WITH_CLI` is not
# set to true, so we expose it as a build-arg.
ARG CARGO_NET_GIT_FETCH_WITH_CLI=false
ENV CARGO_NET_GIT_FETCH_WITH_CLI=$CARGO_NET_GIT_FETCH_WITH_CLI
RUN zypper -n --gpg-auto-import-keys refresh && zypper -n --gpg-auto-import-keys update && zypper --gpg-auto-import-keys ref --force 
#RUN rpm --import https://zypp.postgresql.org/keys/PGDG-RPM-GPG-KEY-SLES15; zypper -n install https://download.postgresql.org/pub/repos/zypp/reporpms/SLES-15-x86_64/pgdg-suse-repo-latest.noarch.rpm
RUN zypper -n install postgresql17 postgresql17-devel postgresql17-contrib postgresql17-server-devel gcc15 gcc15-c++ make automake autoconf libtool gawk python313-devel
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 50
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 50
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-15 50
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-15 50
# To speed up rebuilds, install all of the dependencies before we copy over
# the whole synapse project, so that this layer in the Docker cache can be
# used while you develop on the source
#
# This is aiming at installing the `[tool.poetry.depdendencies]` from pyproject.toml.
COPY --from=requirements /synapse/requirements.txt /synapse/
RUN --mount=type=cache,target=/root/.cache/uv \
  uv pip install --prefix="/install" --no-deps -r /synapse/requirements.txt

# Copy over the rest of the synapse source code.
COPY synapse /synapse/synapse/
COPY rust /synapse/rust/
# ... and what we need to `pip install`.
COPY pyproject.toml README.rst build_rust.py Cargo.toml Cargo.lock /synapse/

# Repeat of earlier build argument declaration, as this is a new build stage.
ARG TEST_ONLY_IGNORE_POETRY_LOCKFILE

# Install the synapse package itself.
# If we have populated requirements.txt, we don't install any dependencies
# as we should already have those from the previous `pip install` step.
RUN \
  --mount=type=cache,target=/root/.cache/uv \
  --mount=type=cache,target=/synapse/target,sharing=locked \
  --mount=type=cache,target=${CARGO_HOME}/registry,sharing=locked \
  if [ -z "$TEST_ONLY_IGNORE_POETRY_LOCKFILE" ]; then \
    uv pip install --prefix="/install" --no-deps /synapse[all]; \
  else \
    uv pip install --prefix="/install" /synapse[all]; \
  fi

###
### Stage 2: Distroless minimal rootfs builder
###
FROM registry.suse.com/bci/bci-base:${SLES_VERSION} AS distroless-builder
#RUN rpm --import https://download.opensuse.org/ports/aarch64/tumbleweed/repo/oss/gpg-pubkey-39db7c82-5f68629b.asc
RUN zypper -n --gpg-auto-import-keys refresh && zypper -n --gpg-auto-import-keys update && zypper --gpg-auto-import-keys ref --force 
RUN zypper -n update
# Copy bci-null.sh script
ADD ./docker/bci-null.sh /tmp/
# Create minimal rootfs with only what Synapse needs
RUN bash /tmp/bci-null.sh \
    python313 \
    libjpeg62 \
    libpq5 \
    libwebp7 \
    xmlsec1 \
    libjemalloc2 \
    curl \ 
    glibc-locale-base \
    findutils \
    sed


###
### Stage 3: runtime
###

FROM registry.suse.com/bci/bci-micro:${SLES_VERSION}

ARG TARGETARCH
ARG GOSU_VER

COPY --from=distroless-builder /tmp/null/rootfs/ /
COPY --from=builder --exclude=.lock /install /usr/local
COPY ./docker/start.py /start.py
COPY ./docker/conf /conf

RUN ln -s /usr/bin/python3.13 /usr/bin/python && \
    ln -s /usr/bin/python3.13 /usr/local/bin/python

# Download gosu binary for the target architecture
RUN curl -L "https://github.com/alessblaze/gosu/releases/download/${GOSU_VER}/gosu-${TARGETARCH}" \
    -o /usr/local/bin/gosu && \
    chmod +x /usr/local/bin/gosu && \
    ln -s /usr/local/bin/gosu /usr/bin/gosu && \
    ln -s /usr/local/bin/gosu /usr/sbin/gosu

EXPOSE 8008/tcp 8009/tcp 8448/tcp
ENTRYPOINT ["/start.py"]
HEALTHCHECK --start-period=5s --interval=15s --timeout=5s \
  CMD curl -fSs http://localhost:8008/health || exit 1
